USE [master]
GO
/****** Object:  Database [BDDJ]    Script Date: 12/6/2024 17:35:16 ******/
CREATE DATABASE [BDDJ]
GO
ALTER DATABASE [BDDJ] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDDJ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDDJ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDDJ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDDJ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDDJ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDDJ] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDDJ] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BDDJ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDDJ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDDJ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDDJ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDDJ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDDJ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDDJ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDDJ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDDJ] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BDDJ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDDJ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDDJ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDDJ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDDJ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDDJ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDDJ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDDJ] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BDDJ] SET  MULTI_USER 
GO
ALTER DATABASE [BDDJ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDDJ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDDJ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDDJ] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BDDJ] SET DELAYED_DURABILITY = DISABLED 
GO
USE [BDDJ]
GO
/****** Object:  Table [dbo].[ADMINISTRADOR]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADMINISTRADOR](
	[_IDAdministrador] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDAdministrador] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[_Nombre] [varchar](30) NOT NULL,
	[_Apellido] [varchar](30) NOT NULL,
	[_IDCliente] [varchar](30) NOT NULL,
	[_CantidadCompras] [bigint] NOT NULL,
	[_DNI] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DETALLE_FACTURA]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DETALLE_FACTURA](
	[_IDDetalleFactura] [bigint] IDENTITY(1,1) NOT NULL,
	[_IDFactura] [bigint] NOT NULL,
	[_IDProducto] [varchar](30) NOT NULL,
	[_PrecioUnitario] [decimal](10, 2) NOT NULL,
	[_Cantidad] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDDetalleFactura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[EMPLEADOS]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EMPLEADOS](
	[_Rol] [varchar](20) NOT NULL,
	[_IDEmpleado] [varchar](30) NOT NULL,
	[_Sueldo] [decimal](10, 2) NULL,
	[_Habilitado] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDEmpleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[FACTURA]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTURA](
	[_IDVendedorFactura] [varchar](30) NOT NULL,
	[_IDClienteFactura] [varchar](30) NOT NULL,
	[_IDFactura] [bigint] IDENTITY(1,1) NOT NULL,
	[_FechaEmision] [datetime] NOT NULL,
	[_Total] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDFactura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOGISTICA]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOGISTICA](
	[_IDLogistica] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDLogistica] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[_IDCreadorProducto] [varchar](30) NOT NULL,
	[_NombreProducto] [varchar](30) NOT NULL,
	[_IDProducto] [varchar](30) NOT NULL,
	[_FechaCreacion] [datetime] NOT NULL,
	[_CantidadEnStock] [bigint] NOT NULL,
	[_CantidadMinimaPermitida] [bigint] NOT NULL,
	[_Costo] [decimal](10, 2) NOT NULL,
	[_Precio] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[_Nombre] [varchar](16) NOT NULL,
	[_Apellido] [varchar](16) NOT NULL,
	[_DNI] [bigint] NOT NULL,
	[_NombreUsuario] [varchar](30) NOT NULL,
	[_Contraseña] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_NombreUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[VENDEDOR]    Script Date: 12/6/2024 17:35:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VENDEDOR](
	[_IDVendedor] [varchar](30) NOT NULL,
	[_CantidadVentas] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[_IDVendedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ADMINISTRADOR]  WITH CHECK ADD  CONSTRAINT [fk_EMPLEADOS_ADMINISTRADOR] FOREIGN KEY([_IDAdministrador])
REFERENCES [dbo].[EMPLEADOS] ([_IDEmpleado])
GO
ALTER TABLE [dbo].[ADMINISTRADOR] CHECK CONSTRAINT [fk_EMPLEADOS_ADMINISTRADOR]
GO
ALTER TABLE [dbo].[DETALLE_FACTURA]  WITH CHECK ADD  CONSTRAINT [fk_FACTURA_DETALLE_FACTURA] FOREIGN KEY([_IDFactura])
REFERENCES [dbo].[FACTURA] ([_IDFactura])
GO
ALTER TABLE [dbo].[DETALLE_FACTURA] CHECK CONSTRAINT [fk_FACTURA_DETALLE_FACTURA]
GO
ALTER TABLE [dbo].[DETALLE_FACTURA]  WITH CHECK ADD  CONSTRAINT [fk_PRODUCTO_DETALLE_FACTURA] FOREIGN KEY([_IDProducto])
REFERENCES [dbo].[PRODUCTO] ([_IDProducto])
GO
ALTER TABLE [dbo].[DETALLE_FACTURA] CHECK CONSTRAINT [fk_PRODUCTO_DETALLE_FACTURA]
GO
ALTER TABLE [dbo].[EMPLEADOS]  WITH CHECK ADD  CONSTRAINT [fk_USUARIOS_EMPLEADOS] FOREIGN KEY([_IDEmpleado])
REFERENCES [dbo].[USUARIOS] ([_NombreUsuario])
GO
ALTER TABLE [dbo].[EMPLEADOS] CHECK CONSTRAINT [fk_USUARIOS_EMPLEADOS]
GO
ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [fk_CLIENTES_FACTURA] FOREIGN KEY([_IDClienteFactura])
REFERENCES [dbo].[CLIENTES] ([_IDCliente])
GO
ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [fk_CLIENTES_FACTURA]
GO
ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [fk_VENDEDOR_FACTURA] FOREIGN KEY([_IDVendedorFactura])
REFERENCES [dbo].[VENDEDOR] ([_IDVendedor])
GO
ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [fk_VENDEDOR_FACTURA]
GO
ALTER TABLE [dbo].[LOGISTICA]  WITH CHECK ADD  CONSTRAINT [fk_EMPLEADOS_LOGISTICA] FOREIGN KEY([_IDLogistica])
REFERENCES [dbo].[EMPLEADOS] ([_IDEmpleado])
GO
ALTER TABLE [dbo].[LOGISTICA] CHECK CONSTRAINT [fk_EMPLEADOS_LOGISTICA]
GO
ALTER TABLE [dbo].[PRODUCTO]  WITH CHECK ADD  CONSTRAINT [fk_Logistica_PRODUCTO] FOREIGN KEY([_IDCreadorProducto])
REFERENCES [dbo].[LOGISTICA] ([_IDLogistica])
GO
ALTER TABLE [dbo].[PRODUCTO] CHECK CONSTRAINT [fk_Logistica_PRODUCTO]
GO
ALTER TABLE [dbo].[VENDEDOR]  WITH CHECK ADD  CONSTRAINT [fk_EMPLEADOS_VENDEDOR] FOREIGN KEY([_IDVendedor])
REFERENCES [dbo].[EMPLEADOS] ([_IDEmpleado])
GO
ALTER TABLE [dbo].[VENDEDOR] CHECK CONSTRAINT [fk_EMPLEADOS_VENDEDOR]
GO
USE [master]
GO
ALTER DATABASE [BDDJ] SET  READ_WRITE 
GO
---------------
use BDDJ
insert USUARIOS([_Nombre], [_Apellido], [_DNI], [_NombreUsuario],[_Contraseña] ) values ('Administrador','Administrador',1,'Administrador','123')-- creamos USUARIO Administrador
insert USUARIOS([_Nombre], [_Apellido], [_DNI], [_NombreUsuario],[_Contraseña] ) values ('Logistica','Logistica',2,'Logistica','123')-- creamos USUARIO Logistica
insert USUARIOS([_Nombre], [_Apellido], [_DNI], [_NombreUsuario],[_Contraseña] ) values ('Vendedor','Vendedor',3,'Vendedor','123')-- creamos USUARIO Vendedor



insert EMPLEADOS([_Rol], [_IDEmpleado], [_Sueldo], [_Habilitado]) values ('Administrador','Administrador',1,'Habilitado')
insert EMPLEADOS([_Rol], [_IDEmpleado], [_Sueldo], [_Habilitado]) values ('Logistica','Logistica',1,'Habilitado')
insert EMPLEADOS([_Rol], [_IDEmpleado], [_Sueldo], [_Habilitado]) values ('Vendedor','Vendedor',1,'Habilitado')

insert ADMINISTRADOR(_IDAdministrador) values ('Administrador')
insert VENDEDOR(_IDVendedor,_CantidadVentas) values ('Vendedor',0)
insert LOGISTICA(_IDLogistica) values ('Logistica')


--------------